TeamProjDjango/src/HomePage/urls.py
from django.urls import path 
from . import views 
app_name ='HomePage'
urlpatterns=[
    path('',views.index,name='index'),
    path('index',views.index,name='index'),
    path('contact',views.contact,name='contact'),
    path('sslist',views.SSlist,name='sslist'),
    path('sswrite',views.SSwrite,name='sswrite'),   
    path('ssupdate/<int:no>',views.SSupdate,name='ssupdate'),   
    path('ssdelete/<int:no>',views.SSdelete,name='ssdelete'),    
    path('logout',views.logout,name='logout'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('update',views.update,name='update'),
    path('delete',views.update,name='delete'),
    path('sspost/<int:no>',views.SSpost,name='sspost'),
    path('about',views.about,name='about'),
    #DABOARD
    path('dalist',views.DAlist,name='dalist'),
    path('dawrite',views.DAwrite,name='dawrite'),   
    path('daupdate/<int:no>',views.DAupdate,name='daupdate'),   
    path('dadelete/<int:no>',views.DAdelete,name='dadelete'),
    path('dapost/<int:no>',views.DApost,name='dapost'), 
    path('damain',views.DAmain,name='damain'),   
    #FRBOARD
    path('frlist',views.FRlist,name='frlist'),
    path('frwrite',views.FRwrite,name='frwrite'),   
    path('frupdate/<int:no>',views.FRupdate,name='frupdate'),   
    path('frdelete/<int:no>',views.FRdelete,name='frdelete'),
    path('frpost/<int:no>',views.FRpost,name='frpost'), 
    path('frmain',views.FRmain,name='frmain'),   
    path('about',views.about,name='about'),
    #OOPBOARD
    path('ooplist',views.OOPlist,name='ooplist'),
    path('oopwrite',views.OOPwrite,name='oopwrite'),   
    path('oopupdate/<int:no>',views.OOPupdate,name='oopupdate'),   
    path('oopdelete/<int:no>',views.OOPdelete,name='oopdelete'), 
    path('ooppost/<int:no>',views.OOPpost,name='ooppost'), 
    #DBMSBOARD
    path('dbmslist',views.DBlist,name='dbmslist'),
    path('dbmswrite',views.DBwrite,name='dbmswrite'),   
    path('dbmsupdate/<int:no>',views.DBupdate,name='dbmsupdate'),   
    path('dbmsdelete/<int:no>',views.DBdelete,name='dbmsdelete'), 
    path('dbmspost/<int:no>',views.DBpost,name='dbmspost'),
]

TeamProjDjango/src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="/static/css/clean-blog.css" rel="stylesheet">
  <link href="/static/css/login.css" rel="stylesheet">
  <link href="/static/css/member.css" rel="stylesheet">
  <link href="/static/css/OOP.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top"
		id="mainNav">
		<div class="container">
			<a class="navbar-brand" href="{% url 'HomePage:index' %}">Learning Man</a>
			<button class="navbar-toggler navbar-toggler-right" type="button"
				data-toggle="collapse" data-target="#navbarResponsive"
				aria-controls="navbarResponsive" aria-expanded="false"
				aria-label="Toggle navigation">
				Menu <i class="fas fa-bars"></i>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item"><a class="nav-link" href="index">About</a>
					</li>
					<li class="nav-item"><a class="nav-link"
						href="{% url 'HomePage:ooplist' %}">OOP</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'HomePage:dbmslist' %}">DBMS</a>
					</li>
					<li class="nav-item"><a class="nav-link" href="{% url 'HomePage:sslist' %}">Server
							Side</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'HomePage:frlist' %}">Frame
							Works</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'HomePage:damain' %}">Data
							Analystics</a></li>
				</ul>
			</div>
		</div>
	</nav>

  <!-- Page Header -->
  <header class="masthead"
		style="background-image: url('/static/img/home-bg.jpg')">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					<div class="site-heading">
						<span class="subheading">Team Project</span>
						<h1>Learning Man</h1>
						<p class="M_btn">
						{% if request.session.userid %}
						<a class="col-lg-8 col-md-10 mx-auto">{{request.session.userid}} 님 환영합니다!</a> <a
								class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:update' %}">회원정보 수정</a>	<a
								class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:logout' %}">로그아웃</a>							
						{% else %}
						<a class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:login' %}">로그인</a> <a
								class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:register' %}">회원가입</a>
						
						{% endif %}
						</p>
					</div>
				</div>
			</div>
		</div>
	</header>
  
{% block content %}
{% endblock content %}
  
   <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">           
          </ul>
          <p class="copyright text-muted">Copyright &copy; Vision 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/js/jquery.dataTables_kor.js"></script>
  <script src="/static/js/dataTables.bootstrap4.js"></script>
  
{% block datatable %}

{% endblock datatable %}

  <!-- Custom scripts for this template -->
  <script src="/static/js/clean-blog.min.js"></script>
  <script src="/static/js/contents_any.js"></script>
  
</body>

</html>

TeamProjDjango/src/templates/base_Dbms.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TeamProject</title>

  <!-- Bootstrap core CSS -->
<link href="/static/vendor/bootstrap/css/bootstrap.min.css"
	rel="stylesheet">

<!-- Custom fonts for this template -->
<link href="/static/vendor/fontawesome-free/css/all.min.css"
	rel="stylesheet" type="text/css">
<link
	href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
	rel='stylesheet' type='text/css'>
<link
	href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
	rel='stylesheet' type='text/css'>

<!-- Custom styles for this template -->
<link href="/static/css/clean-blog.min.css" rel="stylesheet">

<style>
.M_btn>a {
	text-decoration: none;
	color: #fff;
}

.M_btn>a:hover {
	color: #000;
}
</style>

</head>
<body>



	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top"
		id="mainNav" style="font-family: GyeonggiBatangOTF;">
		<div class="container">
			<a class="navbar-brand" href="{% url 'HomePage:index' %}">Learning Man</a>
			<button class="navbar-toggler navbar-toggler-right" type="button"
				data-toggle="collapse" data-target="#navbarResponsive"
				aria-controls="navbarResponsive" aria-expanded="false"
				aria-label="Toggle navigation">
				Menu <i class="fas fa-bars"></i>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
				<li class="nav-item"><a class="nav-link" style="font-size: 13px;" href="index">About</a>
					</li>
					<li class="nav-item"><a class="nav-link"
						style="font-size: 13px;" href="{% url 'HomePage:ooplist' %}">OOP</a></li>
					<li class="nav-item"><a class="nav-link" style="font-size: 13px;" href="{% url 'HomePage:dbmslist' %}">DBMS</a>
					</li>
					<li class="nav-item"><a class="nav-link" style="font-size: 13px;" href="{% url 'HomePage:sslist' %}">Server
							Side</a></li>
					<li class="nav-item"><a class="nav-link" style="font-size: 13px;" href="{% url 'HomePage:frlist' %}">Frame
							Works</a></li>
					<li class="nav-item"><a class="nav-link" style="font-size: 13px;" href="{% url 'HomePage:damain' %}">Data
							Analystics</a></li>
					
				</ul>
			</div>
		</div>
	</nav>


	<!-- Page Header -->
	<header class="masthead"
		style="background-image: url('/static/img/dbms3.png')">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					<div class="site-heading">
						{% if request.session.userid %}
						<p class="M_btn">
							<a class="col-lg-8 col-md-10 mx-auto"
								style="font-family: GyeonggiBatangOTF;"><strong>{{request.session.userid}}</strong>님
								환영합니다.</a> <a class="col-lg-8 col-md-10 mx-auto"
								href="{% url 'HomePage:update' %}"
								style="font-family: GyeonggiBatangOTF;">회원정보 수정</a> <a
								class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:logout' %}"
								style="font-family: GyeonggiBatangOTF;">로그아웃</a>
						</p>
						{% else %}
						<p class="M_btn">
							<a class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:login' %}"
								style="font-family: GyeonggiBatangOTF;">로그인</a> <a
								class="col-lg-8 col-md-10 mx-auto" href="{% url 'HomePage:register' %}"
								style="font-family: GyeonggiBatangOTF;">회원가입</a>
						</p>
						
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</header>
  
{% block content %}
{% endblock content %}
  
   <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">           
          </ul>
          <p class="copyright text-muted">Copyright &copy; Vision 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/js/jquery.dataTables_kor.js"></script>
  <script src="/static/js/dataTables.bootstrap4.js"></script>
  
{% block datatable %}

{% endblock datatable %}

  <!-- Custom scripts for this template -->
  <script src="/static/js/clean-blog.min.js"></script>
  <script src="/static/js/contents_any.js"></script>
  
</body>

</html>