TeamProjDjango/src/HomePage/urls.py
from django.urls import path 
from . import views 
app_name ='HomePage'
urlpatterns=[
    path('',views.index,name='index'),
    path('index',views.index,name='index'),
    path('contact',views.contact,name='contact'),
    path('sslist',views.SSlist,name='sslist'),
    path('sswrite',views.SSwrite,name='sswrite'),   
    path('ssupdate/<int:no>',views.SSupdate,name='ssupdate'),   
    path('ssdelete/<int:no>',views.SSdelete,name='ssdelete'),    
    path('logout',views.logout,name='logout'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('update',views.update,name='update'),
    path('delete',views.update,name='delete'),
    path('sspost/<int:no>',views.SSpost,name='sspost'),
    path('about',views.about,name='about'),
    #DABOARD
    path('dalist',views.DAlist,name='dalist'),
    path('dawrite',views.DAwrite,name='dawrite'),   
    path('daupdate/<int:no>',views.DAupdate,name='daupdate'),   
    path('dadelete/<int:no>',views.DAdelete,name='dadelete'),
    path('dapost/<int:no>',views.DApost,name='dapost'), 
    path('damain',views.DAmain,name='damain'),   
    #FRBOARD
    path('frlist',views.FRlist,name='frlist'),
    path('frwrite',views.FRwrite,name='frwrite'),   
    path('frupdate/<int:no>',views.FRupdate,name='frupdate'),   
    path('frdelete/<int:no>',views.FRdelete,name='frdelete'),
    path('frpost/<int:no>',views.FRpost,name='frpost'), 
    path('frmain',views.FRmain,name='frmain'),   
    path('about',views.about,name='about'),
    #OOPBOARD
    path('ooplist',views.OOPlist,name='ooplist'),
    path('oopwrite',views.OOPwrite,name='oopwrite'),   
    path('oopupdate/<int:no>',views.OOPupdate,name='oopupdate'),   
    path('oopdelete/<int:no>',views.OOPdelete,name='oopdelete'), 
    path('ooppost/<int:no>',views.OOPpost,name='ooppost'), 
    #DBMSBOARD
    path('dbmslist',views.DBlist,name='dbmslist'),
    path('dbmswrite',views.DBwrite,name='dbmswrite'),   
    path('dbmsupdate/<int:no>',views.DBupdate,name='dbmsupdate'),   
    path('dbmsdelete/<int:no>',views.DBdelete,name='dbmsdelete'), 
    path('dbmspost/<int:no>',views.DBpost,name='dbmspost'),
]

TeamProjDjango/src/HomePage/templates/HomePage/NewFile.html
{% extends "base.html" %}
{% block content %}
	<style>
.M_btn>a {
	text-decoration: none;
	color: #fff;
}
.M_btn>a:hover {
	color: #000;
}
</style>
	<!-- Main Content -->
	<div class="container">
		<div class="row">
			<div class="col-sm-5">
				<div class="form-box">
					<div class="form-top">
						<div class="form-top-left">
							<h3>Login to our site</h3>
							<p>Enter username and password to log on:</p>
						</div>
						<div class="form-top-right">
							<i class="fa fa-key"></i>
						</div>
					</div>
					<div class="form-bottom">
						<form role="form" action="" method="post" class="login-form">
							<div class="form-group">
								<label class="sr-only" for="form-username">Username</label> <input
									type="text" name="form-username" placeholder="Username..."
									class="form-username form-control" id="form-username">
							</div>
							<div class="form-group">
								<label class="sr-only" for="form-password">Password</label> <input
									type="password" name="form-password" placeholder="Password..."
									class="form-password form-control" id="form-password">
							</div>
							<button type="submit" class="btn">Sign in!</button>
						</form>
					</div>
				</div>				
			</div>
			<div class="col-sm-1 middle-border"></div>
			<div class="col-sm-1"></div>
			<div class="col-sm-5">
				<div class="form-box">
					<div class="form-top">
						<div class="form-top-left">
							<h3>회원가입</h3>
						</div>
						<div class="form-top-right">
							<i class="fa fa-pencil"></i>
						</div>
					</div>
					<div class="form-bottom">
						<form role="form" action="" method="post"
							class="registration-form">
							<div class="form-group">
								<label class="sr-only" for="form-first-name">First name</label>
								<input type="text" name="form-first-name"
									placeholder="First name..."
									class="form-first-name form-control" id="form-first-name">
							</div>
							<div class="form-group">
								<label class="sr-only" for="form-last-name">Last name</label> <input
									type="text" name="form-last-name" placeholder="Last name..."
									class="form-last-name form-control" id="form-last-name">
							</div>
							<div class="form-group">
								<label class="sr-only" for="form-email">Email</label> <input
									type="text" name="form-email" placeholder="Email..."
									class="form-email form-control" id="form-email">
							</div>
							<div class="form-group">
								<label class="sr-only" for="form-about-yourself">About yourself</label>
								<textarea name="form-about-yourself"
									placeholder="About yourself..."
									class="form-about-yourself form-control"
									id="form-about-yourself"></textarea>
							</div>
							<button type="submit" class="btn">Sign me up!</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endblock content %}
	

TeamProjDjango/src/HomePage/templates/HomePage/dalist.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class = "container">
<table id = "dataTable" class = "table table-bordered" border = "1" align = "center"> 
     	<thead>
			<th align = "center" bgcolor = "#3e5baa" style = "width:10%;"><font color = "white">#</font></th>
			<th align = "center" bgcolor = "#3e5baa" style = "width:65%;"><font color = "white">제목</font></th>
			<th align = "center" bgcolor = "#3e5baa" style = "width:13%;"><font color = "white">작성자</font></th>
			<th align = "center" bgcolor = "#3e5baa" style = "width:12%;"><font color = "white">작성일</font></th>
		</thead>	
		<tbody>
{% if posts %}
{% for post in posts %}
		<tr>		
			<td align = "center" style = "width:10%;"><font color = "black">{{ post.no }}</font></td>
			<td align = "center" style = "width:65%;"><font color = "black"><a href = "dapost/{{ post.no }}">{{ post.title }}</a></font></td>
			<td align = "center" style = "width:13%;"><font color = "black">{{ post.id.name }}</font></td>
			<td align = "center" style = "width:12%;"><font color = "black">{{ post.xdate }}</font></td>			
		</tr>
	 {% endfor %}	
	{% else %}
		게시글 없음
	{% endif %}  
		</tbody>	
			<tr>            	
            	<td align = "center" colspan = "20">
            		<a href = "{% url 'HomePage:dawrite' %}" >
  					질문하기					
  					</a>
            	</td>           	
            </tr>           
        </table> 
</div>
<hr>
{% endblock content %}
{% block datatable %}
<script src = "/static/js/demo/datatables-demo.js"></script>
{% endblock datatable %}

TeamProjDjango/src/HomePage/templates/HomePage/dapost.html
{% extends "base.html" %}
{% block content %}
  		<div class="container">
  		<table class="table table-bordered" style="width:100%">
        	<tr>
                <td style="width:5%">작성자</td>
                <td style="width:40%" colspan="5">
                <input type="text" name = "id" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.id.name}}">               
                </td>
            </tr>
            <tr>
                <td style="width:5%">제목</td>
                <td style="width:24%">
                <input type="text" name = "title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.title}}">
                </td>
                <td style="width:5%">번호</td>
                <td style="width:3%">
                <input type="text" name = "no" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.no}}">
                </td>
                <td  style="width:5%">작성일</td>
                <td  style="width:3%">
                <input type="text" name = "xdate" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.xdate}}">
                </td>
            </tr>
  			<tr>
                <td colspan="6">    
                <textarea rows="20" readonly name = "content" class="form-control" aria-label="With textarea">{{ post.content }}</textarea>                              
                </td>
            </tr>

            </table>  		
  			<br>
  				<br>
			{% if request.session.userid == post.id.id %}
	 		<a class="btn btn-primary" href="{% url 'HomePage:daupdate' post.no %}">수정</a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">삭제</button>
	 		{% elif request.session.userid == 'admin' %}
	 		<a class="btn btn-primary" href="{% url 'HomePage:daupdate' post.no %}">수정</a>	
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">삭제</button>
			{% else %}
			{% endif %}
</div>
  			
  <hr>
  
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">삭제를 진행 하시겠습니까?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        	삭제가 진행되면 복구가 불가능합니다.
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" href="{% url 'HomePage:dadelete' post.no %}">삭제</a>
        <button type="button" class="btn btn-primary" data-dismiss="modal">취소</button>
      </div>
    </div>
  </div>
</div>
        
        

{% endblock content %}
{% block datatable %}

  <script src="/static/js/demo/datatables-demo.js"></script>
{% endblock datatable %}

TeamProjDjango/src/HomePage/templates/HomePage/daupdate.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}	
{% if posts %}
{% for post in posts %}
        <form class = "form-horizontal" action=" " method="post">
      {% csrf_token %}  
           <div class="container">
			<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">제목</span>
			</div>
			<input type="text" id="title" name = "board_title" class="form-control"
				aria-label="Sizing example input"
				aria-describedby="inputGroup-sizing-default"  value="{{ post.title }}">
			</div>
			<div class="input-group">
  			<div class="input-group-prepend">
    			<span class="input-group-text">내용</span>
  			</div>
  			<textarea rows="20" id = "content" name = "board_content" class="form-control" aria-label="With textarea">
  			{{ post.content }}
  
  			</textarea>
  			</div>  			
  			<br>
			<input type="hidden" name = "board_id" value=" {{ post.id }} ">
			<input type="hidden" name = "board_no" value=" {{ post.no }} ">
			<input type="hidden" name = "dbname" value="SSBOARD">
			<button class="btn btn-success" type="submit">수정</button>
	            &nbsp;&nbsp;&nbsp;
     		<a class="btn btn-secondary" href="{% url 'HomePage:dalist' %}"> 리스트로 돌아가기</a>
           </div>
        </form>
        
        <script type = "text/javascript">
			$("#title").change(function(){
				checkTitle($('#title').val());
			});
			$("#content").change(function(){
				checkContent($('#content').val());
			});

			function checkTitle(title){
				if(title.length < 2){
					alert("제목을 2자 이상 설정하시오");
					$('#title').val('').focus();
					return false;
				} else {
					return true;
				}
			}

			function checkContent(content){
				if(content.length < 2){
					alert("내용을 2자 이상 설정하시오");
					$('#content').val('').focus();
					return false;
				} else {
					return true;
				}
			}			
		</script>
        <br>
        {% endblock content %}
		{% block datatable %}

  		<script src="/static/js/demo/datatables-demo.js"></script>
		{% endblock datatable %}

TeamProjDjango/src/HomePage/templates/HomePage/dawrite.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
		<hr>
		<form class = "form-horizontal" action = " " method = "post">		
{% csrf_token %}
		<table class="table table-bordered" align = "center">                             
                <tr>
                    <td align = "center" bgcolor = "#0085a1" style="width:10%"><font color = "white">제목</font></td>
                    <td style="width:50%">
                    	<input class = "form-control" type="text" id="title" name = "title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder = "제목을 입력하세요">
                    </td>
                </tr> 
                <tr>
                    <td align = "center" bgcolor = "#0085a1" style="width:10%"><font color = "white">내용</font></td>
                    <td style="width:50%">
                    	<textarea class = "form-control" name = "content" id = "content" rows = "5" cols = "50" placeholder = "질문 내용을 입력하세요" aria-label="With textarea"></textarea>
                    </td>
                </tr> 
                
                <tr>
                	<td align = "center" colspan = "2">
                		&nbsp;&nbsp;&nbsp;
            			<input type="hidden" name = "id" value="{{user.id}}">
            			<button class = "btn btn-primary2" type = "submit">완료</button>
            			&nbsp;&nbsp;&nbsp;
            			<button class = "btn btn-primary2" type = "reset">삭제</button>
						&nbsp;&nbsp;&nbsp;        			
            			<a class="btn btn-primary2" href="{% url 'HomePage:dalist' %}">취소</a>
                	</td>
                </tr>
			</table>	
		</form>
	
		
</div>
{% if post %}
<script>
document.getElementById('title').value = "{{post.title}}";
document.getElementById('content').value = "{{post.content}}";
</script>
  {% else %}
  
  {% endif %}
<hr>
{% endblock content %}

TeamProjDjango/src/HomePage/templates/HomePage/dbms_post_server.html
{% extends "base_Dbms.html" %}
{% block content %}

 <!-- Post Content -->
  <article>
    <div class="container">
	
		<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default" style="height: 40px; color:#ffffff; background-color:#8B4513; border: none; font-family:GyeonggiBatangOTF; border-radius: 25px 0px 0px 25px;">제목</span>
			</div>
			<input type="text" name = "title" class="form-control"
				aria-label="Sizing example input"
				aria-describedby="inputGroup-sizing-default" readonly value="{{post.title}}"
				style="height: 40px; background-color:#FFFCFA;font-family:GyeonggiBatangOTF; color:#8B4513">
		</div>
		<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text" style="color:#ffffff; background-color:#8B4513; border: none; font-family:GyeonggiBatangOTF; border-radius: 25px 0px 0px 25px;">내용</span>
  	
  </div> 
  	<textarea rows="20" readonly name = "content" class="form-control" aria-label="With textarea" style="background-color:#FFFCFA;font-family:GyeonggiBatangOTF; color:#8B4513"
  >{{ post.content }}</textarea>

  
</div>

	<br>
	
	{% if request.session.userid == post.id.id %}
	 <a class="btn btn-primary" href="{% url 'HomePage:dbmsupdate' post.no %}" style="border-radius: 12px; border: none; background-color: #8B4513;font-size: 15px; font-family: GyeonggiBatangOTF">
	  수정</a>
	  
	<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" style="border-radius: 12px; border: none; background-color: #CD0000; font-size: 15px; font-family: GyeonggiBatangOTF"
	>삭제</button>	
	
	 {% elif request.session.userid == 'admin' %}
	 <a class="btn btn-primary" href="{% url 'HomePage:dbmsupdate' post.no %}" style="border-radius: 12px; border: none; background-color: #8B4513; font-size: 15px; font-family: GyeonggiBatangOTF"
	 >수정</a>	
	 
	<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" style="border-radius: 12px; border: none; background-color: #CD0000;  font-size: 15px; font-family: GyeonggiBatangOTF"
	>삭제</button>
	{% else %}
	{% endif %}
	
</div>
  </article>
  	
	
  <hr>
  
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel" style="font-family:GyeonggiBatangOTF;">정말로 삭제 하시겠습니까?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="font-family:GyeonggiBatangOTF;">
        	삭제한 뒤에는 복구할 수 없습니다.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" style="font-family:GyeonggiBatangOTF;">취소</button>
        <a class="btn btn-danger" href="{% url 'HomePage:dbmsdelete' post.no %}" style="font-family:GyeonggiBatangOTF;">삭제</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

TeamProjDjango/src/HomePage/templates/HomePage/frpost.html
{% extends "base.html" %}
{% block content %}
  		<div class="container">
  		<table class="table table-bordered" style="width:100%">
        	<tr>
                <td style="width:5%">작성자</td>
                <td style="width:40%" colspan="5">
                <input type="text" name = "id" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.id.name}}">               
                </td>
            </tr>
            <tr>
                <td style="width:5%">제목</td>
                <td style="width:24%">
                <input type="text" name = "title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.title}}">
                </td>
                <td style="width:5%">번호</td>
                <td style="width:3%">
                <input type="text" name = "no" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.no}}">
                </td>
                <td  style="width:5%">작성일</td>
                <td  style="width:3%">
                <input type="text" name = "xdate" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly value="{{post.xdate}}">
                </td>
            </tr>
  			<tr>
                <td colspan="6">    
                <textarea rows="20" readonly name = "content" class="form-control" aria-label="With textarea">{{ post.content }}</textarea>                              
                </td>
            </tr>

            </table>  		
  			<br>
  				<br>
			{% if request.session.userid == post.id.id %}
	 		<a class="btn btn-primary" href="{% url 'HomePage:daupdate' post.no %}">수정</a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">삭제</button>
	 		{% elif request.session.userid == 'admin' %}
	 		<a class="btn btn-primary" href="{% url 'HomePage:daupdate' post.no %}">수정</a>	
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">삭제</button>
			{% else %}
			{% endif %}
</div>
  			
  <hr>
  
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">삭제를 진행 하시겠습니까?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        	삭제가 진행되면 복구가 불가능합니다.
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" href="{% url 'HomePage:dadelete' post.no %}">삭제</a>
        <button type="button" class="btn btn-primary" data-dismiss="modal">취소</button>
      </div>
    </div>
  </div>
</div>
        
        

{% endblock content %}
{% block datatable %}

  <script src="/static/js/demo/datatables-demo.js"></script>
{% endblock datatable %}

TeamProjDjango/src/HomePage/templates/HomePage/frupdate.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}	
{% if posts %}
{% for post in posts %}
        <form class = "form-horizontal" action=" " method="post">
      {% csrf_token %}  
           <div class="container">
			<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">제목</span>
			</div>
			<input type="text" id="title" name = "board_title" class="form-control"
				aria-label="Sizing example input"
				aria-describedby="inputGroup-sizing-default"  value="{{ post.title }}">
			</div>
			<div class="input-group">
  			<div class="input-group-prepend">
    			<span class="input-group-text">내용</span>
  			</div>
  			<textarea rows="20" id = "content" name = "board_content" class="form-control" aria-label="With textarea">
  			{{ post.content }}
  
  			</textarea>
  			</div>  			
  			<br>
			<input type="hidden" name = "board_id" value=" {{ post.id }} ">
			<input type="hidden" name = "board_no" value=" {{ post.no }} ">
			<input type="hidden" name = "dbname" value="SSBOARD">
			<button class="btn btn-success" type="submit">수정</button>
	            &nbsp;&nbsp;&nbsp;
     		<a class="btn btn-secondary" href="{% url 'HomePage:dalist' %}"> 리스트로 돌아가기</a>
           </div>
        </form>
        
        <script type = "text/javascript">
			$("#title").change(function(){
				checkTitle($('#title').val());
			});
			$("#content").change(function(){
				checkContent($('#content').val());
			});

			function checkTitle(title){
				if(title.length < 2){
					alert("제목을 2자 이상 설정하시오");
					$('#title').val('').focus();
					return false;
				} else {
					return true;
				}
			}

			function checkContent(content){
				if(content.length < 2){
					alert("내용을 2자 이상 설정하시오");
					$('#content').val('').focus();
					return false;
				} else {
					return true;
				}
			}			
		</script>
        <br>
        {% endblock content %}
		{% block datatable %}

  		<script src="/static/js/demo/datatables-demo.js"></script>
		{% endblock datatable %}

TeamProjDjango/src/HomePage/templates/HomePage/frwrite.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
		<hr>
		<form class = "form-horizontal" action = " " method = "post">		
{% csrf_token %}
		<table class="table table-bordered" align = "center">                             
                <tr>
                    <td align = "center" bgcolor = "#0085a1" style="width:10%"><font color = "white">제목</font></td>
                    <td style="width:50%">
                    	<input class = "form-control" type="text" id="title" name = "title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder = "제목을 입력하세요">
                    </td>
                </tr> 
                <tr>
                    <td align = "center" bgcolor = "#0085a1" style="width:10%"><font color = "white">내용</font></td>
                    <td style="width:50%">
                    	<textarea class = "form-control" name = "content" id = "content" rows = "5" cols = "50" placeholder = "질문 내용을 입력하세요" aria-label="With textarea"></textarea>
                    </td>
                </tr> 
                
                <tr>
                	<td align = "center" colspan = "2">
                		&nbsp;&nbsp;&nbsp;
            			<input type="hidden" name = "id" value="{{user.id}}">
            			<button class = "btn btn-primary2" type = "submit">완료</button>
            			&nbsp;&nbsp;&nbsp;
            			<button class = "btn btn-primary2" type = "reset">삭제</button>
						&nbsp;&nbsp;&nbsp;        			
            			<a class="btn btn-primary2" href="{% url 'HomePage:dalist' %}">취소</a>
                	</td>
                </tr>
			</table>	
		</form>
	
		
</div>
{% if post %}
<script>
document.getElementById('title').value = "{{post.title}}";
document.getElementById('content').value = "{{post.content}}";
</script>
  {% else %}
  
  {% endif %}
<hr>
{% endblock content %}

TeamProjDjango/src/HomePage/templates/HomePage/ooplist.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


 <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-10 mx-auto">
        <div class="post-preview">
            <h2 class="post-title">
				OOP
            </h2>
            <h3 class="post-subtitle" style="margin-bottom: 80px;">
              	객체지향 프로그래밍
            </h3>
        </div>
    	<div class="add_btn">
			<p>
				<a href="{% url 'HomePage:oopwrite' %}">글쓰기</a>
			</p>			
		</div>
        <hr>
		<div class="OOP_board_box">
			<div class="b_header">
				<p class="OOP_no">글 번호</p>
				<p class="OOP_title"> 제목</p>
				<p class="OOP_id">글쓴이</p>
				<p class="OOP_date">게시일</p>
			</div>
		{% if posts %}
  {% for post in posts %}
		
			<div class="b_content">
				<p class="OOP_no">{{ post.no }}</p>
				<p class="OOP_title"><a href="ooppost/{{ post.no }}">{{ post.title }}</a></font></p>
				<p class="OOP_id">{{ post.id.name }}</p>
				<p class="OOP_date">{{ post.xdate }}</p>
			</div>
		{% endfor %}	
	{% else %}
		자료가 없습니다.
	{% endif %} 
		</div>
	</div>
  </div>




  

  <hr>

{% endblock content %}
{% block datatable %}

  <script src="/static/js/demo/datatables-demo.js"></script>
{% endblock datatable %}

TeamProjDjango/src/HomePage/templates/HomePage/oopwrite.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-10 mx-auto">
        <div class="post-preview">
            <h2 class="post-title">
				OOP
            </h2>
            <h3 class="post-subtitle" style="margin-bottom: 80px;">
              	객체지향 프로그래밍
            </h3>
        </div>
        <hr>
		<div class="container">
			<form class = "form-horizontal" action = "" method = "post">
			{% csrf_token %}		
				<div class="input-group mb-3">
				<div class="input-group-prepend">
					<span class="input-group-text" id="inputGroup-sizing-default">제목</span>
					</div>
        			<input type="text" id="title" name = "title" class="form-control"
        				aria-label="Sizing example input"
        				aria-describedby="inputGroup-sizing-default">
				</div>
				<div class="input-group">
    				<div class="input-group-prepend">
    					<span class="input-group-text">내용</span>
    				</div>
  					<textarea rows="20" id = "content" name = "content" class="form-control" aria-label="With textarea"></textarea>
  				</div>
				<input type="hidden" name = "id" value="{{user.id}}">
				<button class="btn btn-success" type="submit">저장</button>
				<a class="btn btn-secondary" href="{% url 'HomePage:oopwrite' %}"> 리스트로 돌아가기</a>
			</form>
		</div>
	</div>
  </div>
  <hr>

{% if post %}
<script>
document.getElementById('title').value = "{{post.title}}";
document.getElementById('content').value = "{{post.content}}";
</script>
  {% else %}
  
  {% endif %}

{% endblock content %}